### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AgentScarlet** [rydoginator/ACNL-NTR-Cheats#54]
it says this has seeder? does it work?? does it work online?? im looking for the rock plugin that the fb groups are using. i want to be able to help my friends who live nearby with their towns is all. and i aint having no luck finding it. ive been stuck on the island 2 times now due to someone using something of the sort. and im tired of it.

**Comment by LeviSpecialzz** [comment]
The seeder is Real Time World Edit in the Environment folder. It does work in single player. It does not work online.
