### ISSUE TITLE
Please suppport also romhack cia!

### ISSUE THREAD

**Issue by 38b** [rydoginator/ACNL-NTR-Cheats#57]
**Issue:**

I can't use your plugin if I installed ACNL romhack cia
This plugin said "Your ACNL version isn't supported! Make sure you have the 1.5 update installed!"
But romhack cia I installed is 1.5 ver.

**Version of plugin:**

4.1

**NTR Version used:**

NTR v3.6

**Type of 3DS:**

Old 3DS

**3DS Firmware Version:**

11.8.0-39J

**CFW on 3DS:**

Luma3DS ver.9.1

**ACNL Version:**

ACNL with the v1.5 update,but it is installed romhack cia

**Source of game:**

CIA downloaded from elsewhere

**Language & Region:**

Japanese

**Extra description of event:**

No problem. 

**It is also recommended to send us a luma crash dump.
The crash dump will be located at `SD:/luma/dumps/arm11` or `SD:/luma/dumps/arm9`.**

Luma doesn't crash.

I am sorry that my English is so bad.
And my romhack makes ACNL able to drop and bury

**Comment by Slattz** [comment]
This is an issue with your rom hack, not the plugin.

**Comment by 38b** [comment]
Thank you for telling me!
I'll try again to make my romhack.
