### ISSUE TITLE
What is the “quick menu” and how do I access it?

### ISSUE THREAD

**Issue by kokichioumalovesme** [rydoginator/ACNL-NTR-Cheats#60]
I heard some cheats such as the inventory box extender requires opening the “quick menu”, but I can’t find it. What do I do to access it? I tried looking everywhere I could sorry if I didn’t look hard enough. Love the plug-in by the way. Very fun

**Comment by LeviSpecialzz** [comment]
The quick menu is an easy to access menu that allows you to change your character, get sets, and more. You can access the menu by pressing the X button and the R button at the same time.

**Comment by kokichioumalovesme** [comment]
The quick menu doesn’t seem to be working for me. Maybe it’s just my 3DS or I’m not getting the timing right but I’m pressing those buttons and it just opens my pockets

**Comment by kokichioumalovesme** [comment]
Ah, Nevermind. I just had to hold them down for a sec. I’ll close this now since you answered my question. Thanks!

**Comment by LeviSpecialzz** [comment]
No problem
